import type { Metadata } from "next";
import { Geist, Geist_Mono, Bungee_Inline, Space_Grotesk, Rajdhani, Manrope, Inter, Lora, Montserrat } from "next/font/google";
 import'./globals.css'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-manrope',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-inter',
});

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-lora',
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-Space',
});

const rajdhani= Rajdhani({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-rajdhani',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Ayobami Aina's portfolio",
  description: "Generated by Ayobami Aina",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${montserrat.variable} ${lora.variable} ${manrope.variable} ${spaceGrotesk.variable} ${rajdhani.variable} ${inter.variable} `}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       className="font-lora"
      
      >
        {children}
      </body>
    </html>
  );
}
